export const  UPDATE_EXPRESSION = 'UPDATE_EXPRESSION';
export const   SLICE_EXPRESSION =  'SLICE_EXPRESSION';
export const   CLEAR_EXPRESSION =  'CLEAR_EXPRESSION';
export const FIRSTENTRY_DISPLAY = 'FIRSTENTRY_DISPLAY';
export const     UPDATE_DISPLAY = 'UPDATE_DISPLAY';
export const     RESULT_DISPLAY = 'RESULT_DISPLAY';
export const      CLEAR_DISPLAY = 'CLEAR_DISPLAY';
export const TOGGLE_FIRSTENTRY  = 'TOGGLE_FIRSTENTRY';
